### ISSUE TITLE
ServerQuery options (as array) are not passed correctly

### ISSUE THREAD

**Issue by Typhoon31** [nikeee/node-ts#11]
Hi,

I got following problem:

If I want to execute a command with parameters, for example: 
```javascript
sq.send('clientlist', {}, ['uid', 'away', 'voice', 'times', 'groups', 'info', 'icon', 'country', 'ip', 'badges'])
```
It is passing the parameter as:
> clientlist {} 0=uid, 1=away, 2=voice, 3=times, 4=groups, 5=info, 6=icon, 7=country, 8=ip, 9=badges

So your lib sends the following command to the server:
> clientlist -0 -1 -2 -3 -4 -5 -6 -7 -8 -9

Changing line 106 and 107 in node-ts.js from:

```javascript
for (let v in options)
   tosend += " -" + StringExtensions.tsEscape(v);
```
...to:
```javascript
for (var i = 0; i < options.length; i++)
   tosend += " -" + StringExtensions.tsEscape(options[i]);
```

... fixes the problem, as the for...in statement is meant to enumerate object properties, and using it for iterating arrays should be avoided.

I made a pull-request fixing this problem: #12

**Comment by nikeee** [comment]
> for...in statement is meant to enumerate object properties
I think it meant to be for... of instead. Thanks for reporting.
