### ISSUE TITLE
channeladdperm no longer working after ts update

### ISSUE THREAD

**Issue by Sir-Will** [nikeee/node-ts#13]
hey,

I updated my ts server few days ago now the `channeladdperm` is somehow broken.

```
[24.01 - 23:10:30] [DIR]   { cmd: 'channeladdperm',
  options: [],
  text: 'channeladdperm cid=39472 permid=80|permid=122|permid=130|permid=137|permid=139|permid=141|permid=234|permid=236|permid=240|permid=242|permid=244 permvalue=75|permvalue=4|permvalue=60|permvalue=1|permvalue=2|permvalue=3|permvalue=6|permvalue=7|permvalue=8|permvalue=5|permvalue=9',
  parameters: 
   { cid: 39472,
     permid: [ 80, 122, 130, 137, 139, 141, 234, 236, 240, 242, 244 ],
     permvalue: [ 75, 4, 60, 1, 2, 3, 6, 7, 8, 5, 9 ] },
  error: { id: 1539, msg: 'parameter not found' },
  response: null,
  rawResponse: null }

```

I don't see any changes in the query manual and I can't figure out what parameter is missing.

**Comment by nikeee** [comment]
The error reminds me of this:
https://github.com/nikeee/node-ts/issues/10#issuecomment-185308531

Maybe they changed the array parsing to match their docs.

**Comment by Sir-Will** [comment]
Do you know how to fix this issue?

**Comment by nikeee** [comment]
I am still investigating.

**Comment by nikeee** [comment]
What version is your server? Have you tried using an older version of node-ts?

**Comment by Sir-Will** [comment]
3.0.13.6

No didn't try other versions.

**Comment by Sir-Will** [comment]
Oh man, just found the issue.
Updated my test server to try reproducing the issue but I couldn't. Then I checked for the node-ts version and realized that I never updated the package on my live bot.
I was sure that I already had it working on the live server so I thought it's the teamspeak version.

Sorry about the trouble.
