### ISSUE TITLE
3.x installation issues

### ISSUE THREAD

**Issue by DeltaCore** [nikeee/node-ts#16]
I recently updated the version of this module and every 3.x version seems to not install correctly.

Here is the node_modules/node-ts with version 2.1.2: http://prntscr.com/mq2xim
and here with version >=3.0.1: http://prntscr.com/mq2xvy

Any logs i can give you to track down the problem?

- Marcel

**Comment by nikeee** [comment]
The `.npmignore` had a wrong entry. It is fixed in `^3.0.3`. Also reduced the dependencies.
