### ISSUE TITLE
Import problems

### ISSUE THREAD

**Issue by DeltaCore** [nikeee/node-ts#17]
Hehe, me again...

Tried out the new version and still got some wierd stuff:

This gives me a module not found error (http://prntscr.com/mqknwv):
```ts
import { TeamSpeakClient } from "node-ts";
```
This does not (http://prntscr.com/mqko9j):
```ts
import { TeamSpeakClient } from "node-ts/lib/node-ts";
```

Sorry to bother you with more bugs :P Any ideas?

- Marcel

**Comment by nikeee** [comment]
Thanks for reporting this! This is correct. The entries `main` and `types` are not pointing to valid files (any more). I'll fix this tomorrow.

**Comment by DeltaCore** [comment]
Cool. Glad I can help :)

**Comment by nikeee** [comment]
Could you check if this is resolved in 3.0.7? I'm currently on my phone.

**Comment by DeltaCore** [comment]
It’s like 0:30am here. Will check when I get up again :D

**Comment by DeltaCore** [comment]
Everything is working fine. I finally had time to test. Good job 👍

- Marcel
