### ISSUE TITLE
Query login issues

### ISSUE THREAD

**Issue by DeltaCore** [nikeee/node-ts#18]
I don't know what changed, but the as of version 3 i can no longer connect to my teamspeak server via this api. With version 2.1.2 everything was fine. Is there somekind of minimum version of the ts server required for the use with this api version 3?

The exact same code works with node-ts@2.1.2 but not with >3.0.6

Any ideas?

- Marcel

**Comment by nikeee** [comment]
It may be have to do with #15. I'll take a look at this.

**Comment by nikeee** [comment]
FYI: The current master branch is broken. I'll rewrite some parts this week.

**Comment by DeltaCore** [comment]
Yeah i noticed that. I had to rename all ResponseData variable names because they are case-sensitive xd

I "forked" that to my own gitlab server: https://git.ccmob.net/marcel/node-ts if you want to have a look what i changed. In that form it's working for me. I "reverted" #15 and i think implemented some interfaces and query functions.

Marcel

**Comment by nikeee** [comment]
I've just rewrote parts of the library and released it as `4.0.x`. Note that you now have to call the `connect` function, which returns a promise.

The sample in the readme was updated accordingly.

**Comment by DeltaCore** [comment]
Cool, 
will have a look at it on the weekend.

From the look of it, the issue with the query variables returned from a command is still all caps, which did not worked for me. I had to lower case them all and correct some of them because the client info for example is outdated ^^ But that i will test aswell and will give you feedback again if nedded :)

Marcel

**Comment by nikeee** [comment]
> with the query variables returned from a command is still all caps

Does this mean that all the interface members that are entirely upper cased are actually delivered lower-cased?

**Comment by nikeee** [comment]
Can you confirm that it is resolved?

**Comment by DeltaCore** [comment]
Hey,

sorry for replying to late, hadn't had a chance to test yet, was kind of busy :P

I will test it somewhere over the weekend and will get back to you
