### ISSUE TITLE
i get module.js error

### ISSUE THREAD

**Issue by sbslord** [nikeee/node-ts#5]
i use your simple code with my data and run and i get this error.
Cannot find module './node_modules/line-readable-stream/LineReadableStream'
i used npm install line-readble-stream too but problem again this.

**Comment by nikeee** [comment]
Sorry for being so late. I have changed the toolchain and managed to find a proper solution.
See the readme for instructions:
https://github.com/nikeee/node-ts/blob/master/README.md
I am also using `byline` now (instead of `line-readable-stream`).

Does this solve your issue?

**Comment by nikeee** [comment]
THis might be solved now.
